### ISSUE TITLE
lassoregress doesn't replicate?

### ISSUE THREAD

**Issue by dpaserma** [wilbur-t/elasticreg#15]
Huh?

Running lassoregress on the same identical data twice doesn't yield the same results. It does if you set the seed before running it? 

See attached log file.

Is this how it's supposed to be?
[lassoregress_test.log](https://github.com/wilbur-t/elasticregress/files/1640940/lassoregress_test.log)

**Comment by wilburtownsend** [comment]
Yes, lassoregress uses [K-fold cross validation](https://en.wikipedia.org/wiki/Cross-validation_(statistics)#k-fold_cross-validation) to find the optimal lambda parameter. K-fold cross validation involves randomly partitioning the data, and different random partitions could result in different values of lambda and thus different estimated beta. These differences shouldn't be substantial.
