### ISSUE TITLE
lassoregress has a bug

### ISSUE THREAD

**Issue by Ade-Omari** [wilbur-t/elasticreg#16]
Hi Wilbur, I am using a lasso regression in Stata. when I run the command below to regress toilet (demand) onto the trans_from (state) variable Stata gives me this error. Can you help me figure it out?

lassoregress toilet trans_from
             covUpdate():  3498  Beta became missing. Please report this bug to https://github.com/wilbur-t/elasticregress.
              findBeta():     -  function returned error
           findAllBeta():     -  function returned error
   crossValidateLambda():     -  function returned error
         notEstimation():     -  function returned error
                 <istmt>:     -  function returned error
r(3498);

Ade

**Comment by wilburtownsend** [comment]
Hi @Ade-Omari , thanks for reporting this. Are you able to send through the code / data which led to the bug?

**Comment by Ade-Omari** [comment]
Hi Wilbur,

              Attached is the code and data-set; I am using Stata 14.2.
Please forgive the less than savvy nature of my code, I only started
learning 2 months ago. What I am trying to do is estimate (future) demand
for the services indicated in the 1st tabstat, using Markov chains to
estimate transition probabilities (from state to state) captured in matrix
abc (for toilet, I omitted the other services for the time being). The
formed matrix abc is an ill-conditioned one, i.e. the LU factorization
(AX=b) does not converge (b is the mean demand in each classified state).
Hence I used the pinv-function (within the LU factorization) to stabilize
the estimate, I assumed the X vector gives estimates for de-seasonalized
data. I multiplied those estimates by a seasonal factor to mimic demand
(variance) in/of each state (Super, Normal and Sub-Normal).

             I then train my estimate by multiplying each the estimate of
each state by the transition intensity (out of each state) provided by the
Markov chain. I test the train_Toil (estimate) by calculating the mean
squared error of the train_Toil minus the actual demand for the period in
question. I am currently trying to compare this value to the MSE of a
moving average estimate; the assumption is which ever estimate consistently
gives the lowest error is the better estimate.

             I also wanted to introduce a new estimator of demand, using a
lasso regression of *toilet* (demand) onto the *trans_from* variable and
that is where the code becomes buggy. Now if I use lassoregress with*
toilet* (demand) and demand for another service e.g. *flushvalve*, the
lassoregress function works fine. Again, if I type lassoregress* toilet*
*trans_from* ... then the problem arises. I don't have lassoregress *toilet
trans_from* ... in my .do file.You will have to call that regression after
the .do file runs; but I am running an elasticregress function in the .do
file and you can see it works fine (although the variables are too
correlated - its just a diagnostic test).

             I really hope the explanation of my code is clear enough. If I
can get the lasso regression to work well for* toilet* and *trans_from*,
then I can have a third estimate which may converge (unlike the Markov
chain) because of the reduction of the coefficients. Then I can run a Bayes
Metropolis-Hasting (bayesmh) function and the a Gelman-Rubin (grubin)
function to test which mean squared error (MSE) of the three estimates is
lower or more readily converges.

Thanks for the swift reply and any subsequent alterations you make, to
rectify the problem.

A. Omari

**Comment by wilburtownsend** [comment]
Hi @Ade-Omari -- you replied over email, and the attachments were lost. Could you send them to wilbur.townsend@gmail.com?

**Comment by wilburtownsend** [comment]
Fixed by commit https://github.com/wilbur-t/elasticregress/commit/31b41ee3729320eb2e13c8bf977f450648a0730e
