### ISSUE TITLE
Elasticregress doesn't run on Stata 16?

### ISSUE THREAD

**Issue by tbaseler14** [wilbur-t/elasticreg#18]
Ever since I updated to Stata 16 from Stata 15, my lasso code won't run. I get the following error regardless of the underlying data, the number of variables, or the options I'm choosing.

covUpdate():  3498  Beta became missing.

**Comment by wilburtownsend** [comment]
Hi @tbaseler14 -- could you send through some code/data that replicates the issue? Thanks

**Comment by tbaseler14** [comment]
*** editing to set the seed to default, since the problem only arises when lasso picks a nonempty subset of variables. when every variable is excluded, the code finishes without issue. the following seed will generate the bug for me.

Thanks @wilburtownsend - as far as I can tell it happens on anything. For example:

**Code:** 

clear all
set obs 10

set seed 123456789

gen y = runiform()
gen x1 = runiform()
gen x2 = runiform()

lassoregress y x1 x2

**Output:**

. lassoregress y x1 x2
                assert():  3498  assertion is false
            updateCovX():     -  function returned error
             covUpdate():     -  function returned error
              findBeta():     -  function returned error
           findAllBeta():     -  function returned error
         notEstimation():     -  function returned error
                 <istmt>:     -  function returned error

**Comment by wilburtownsend** [comment]
Sorry for the delay getting to this (have just started my first year of grad school.....)

I am pretty sure the bug is coming from Stata's end. I've posted about it here:
https://www.statalist.org/forums/forum/general-stata-discussion/mata/1518954-weird-breaking-change-in-stata-16-with-views-cross-and-column-indexing

Will update when possible.

**Comment by wilburtownsend** [comment]
This has been resolved in the latest Stata update.

**Comment by tbaseler14** [comment]
Thank you so much for taking care of this! Really appreciate it.

**Comment by TeodoraNTsankova** [comment]
Hi, I am running lassoregress now with Stata 16 (both up to date) and I get the following error:

assert():  3498  assertion is false

I was able to run it on my previous machine so this is very frustrating.

**Comment by wilburtownsend** [comment]
Hi TeodoraNTsankova -- can you post code that replicates the problem? I just updated Stata and don't have any problems.

**Comment by TeodoraNTsankova** [comment]
Apologies, here it is:

\documentclass[notitlepage,12pt]{article}

\usepackage{graphicx}
\usepackage[update,prepend]{epstopdf}

\begin{document}

\begin{figure}
	\begin{center}
	\includegraphics[width=0.85\textwidth]{"figure_2a"}
	\end{center}	
\end{figure}
	
\end{document}

**Comment by wilburtownsend** [comment]
lol buddy

**Comment by TeodoraNTsankova** [comment]
Apologies for reposting - I have multiple open question raised on github.

Here is the code:

global X_vars x1 x2 x3 x4 x5 x6 x7 x8 x9 x10

foreach depvar in y1 y2 {

	lassoregress `depvar' $X_vars
	
	local lasso_controls = e(varlist_nonzero)

	eststo `depvar': reg `depvar' Treatment_dumy `lasso_controls', robust
	
}

Now, I substituted with the following command which works in Stata 16:

foreach depvar in y1 y2 {

	lasso linear `depvar' $X_vars
	
	local lasso_controls = e(allvars_sel)
	
	eststo `depvar': reg `depvar' Treatment_dumy `lasso_controls', robust
	
}

Thanks for the help.

**Comment by wilburtownsend** [comment]
I'm not running into any issues with that code. Can you post the data which is causing bugs?

**Comment by TeodoraNTsankova** [comment]
Apologies, but the data is confidential. 

I did see that others say that the problem was resolved. I re-installed Stata and just downloaded the package as I have a new laptop. The code used to work on my old one so it is unlikely that I have made a mistake.  I tried with a different data set just in case and I still get the "assert():  3498  assertion is false" error.

**Comment by wilburtownsend** [comment]
ok. can you simulate a dataset that replicates the issue?

**Comment by TeodoraNTsankova** [comment]
Sure, I am attaching it (dta was not allowed so it is an xlsx file). I just created random values and I get the same error. Thank you for trying to help.

[sample_data.xlsx](https://github.com/wilburtownsend/elasticregress/files/5393524/sample_data.xlsx)

**Comment by wilburtownsend** [comment]
I'm not getting any errors when I run lassoregress on that data

**Comment by TeodoraNTsankova** [comment]
It must be something with either the version of the package / Stata or something wrong with my settings. In any case, I do not think we can resolve it this way. Thank you very much for trying. If you have any ideas, let me know of course.

**Comment by malena-acuna** [comment]
Hey! I also have Stata 16 now and I am not being able to run code I was able to run before reinstalling Stata. Unfortunately, the data is also confidential. This is the error I am getting:

                   assert():  3498  assertion is false
            updateCovX():     -  function returned error
             covUpdate():     -  function returned error
              findBeta():     -  function returned error
           findAllBeta():     -  function returned error
         notEstimation():     -  function returned error
                 <istmt>:     -  function returned error

@TeodoraNTsankova or whoever knows, did you find an alternative solution?
Thank you so much in advance!!

**Comment by TeodoraNTsankova** [comment]
I did not manage to resolve it and used the lasso linear command
