### ISSUE TITLE
Lassoregress r(3498) bug

### ISSUE THREAD

**Issue by noumedem** [wilbur-t/elasticreg#20]
Hi Wilbur,

I am running the lassoregress command and I have been getting the r(3498) error from Stata (Please see below). I must say I ran that same command on the same exact data back in April 2019 and everything was running smoothly. Now I can't replicate my results. I keep on getting the same error. I read others have had the same error message and I was wondering how to fix it. Thanks for your help.
  assert():  3498  assertion is false
            updateCovX():     -  function returned error
             covUpdate():     -  function returned error
              findBeta():     -  function returned error
           findAllBeta():     -  function returned error
         notEstimation():     -  function returned error
                 <istmt>:     -  function returned error

Best

**Comment by wilburtownsend** [comment]
Hi there. The issue should be resolved in the latest Stata patch. Please use the command `update all`.

**Comment by noumedem** [comment]
Hi Wilbur,

It works fine now. 
Many thanks for your help.
